# Generated by Django 4.1 on 2022-08-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='STOREHOUSE', max_length=200),
        ),
    ]
