# Generated by Django 4.1 on 2022-08-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storehouse', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Snippet',
            field=models.CharField(default='Click Link Above To Read Post', max_length=200),
        ),
    ]
